name: RELEASE-PROD

on:
  workflow_dispatch:
    inputs:
      hotfix:
        type: choice
        description: "Is this a hotfix release?"
        required: false
        default: "false"
        options:
          - true
          - false

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write
  actions: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        if: ${{ github.event.inputs.hotfix == 'false' }}
        uses: changesets/action@v1
        with:
          version: npm run release:version
          publish: npm run release:tag
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Branch
        if: ${{ github.event.inputs.hotfix == 'true' }}
        id: create-branch
        run: |
          branch_name="hotfix_release_branch"
          git checkout -b $branch_name
          git push origin $branch_name
          echo "::set-output name=branch_name::$branch_name"

      - name: Bump Version, Tag Release, and Create Pull Request
        if: ${{ github.event.inputs.hotfix == 'true' }}
        run: |
          npm run release:version
          npm run release:tag
          branch_name="${{ steps.create-branch.outputs.branch_name }}"
          echo "Creating Pull Request to hotfix_release_branch..."
          echo "::set-output name=branch_name::$branch_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Create the pull request to merge changes into hotfix_release_branch
          HOTFIX_BRANCH: ${{ steps.create-branch.outputs.branch_name }}
      - name: Create Pull Request to hotfix_release_branch
        if: ${{ github.event.inputs.hotfix == 'true' }}
        uses: peter-evans/create-pull-request@v3
        with:
          base: hotfix_release_branch
          branch: ${{ env.HOTFIX_BRANCH }}
          title: "Merge changes from ${{ env.HOTFIX_BRANCH }}"
          labels: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
