name: RELEASE-PROD

on:
  workflow_dispatch:
    inputs:
      hotfix:
        type: choice
        description: "Is this a hotfix release?"
        required: false
        default: "false"
        options:
          - true
          - false

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write
  actions: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        if: ${{ github.event.inputs.hotfix == 'false' }}
        uses: changesets/action@v1
        with:
          version: pnpm release:version
          publish: pnpm release:tag
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout to Current Branch
        if: ${{ github.event.inputs.hotfix == 'true' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Changesets CLI
        if: ${{ github.event.inputs.hotfix == 'true' }}
        run: pnpm add -g @changesets/cli

      - name: Bump Version, Tag Release, and Create Pull Request
        if: ${{ github.event.inputs.hotfix == 'true' }}
        run: |
          pnpm changeset version
          pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only run if hotfix flag is true
      - name: Create Pull Request to hotfix_release_branch
        if: ${{ github.event.inputs.hotfix == 'true' }}
        uses: peter-evans/create-pull-request@v3
        with:
          base: hotfix_release_branch
          branch: ${{ github.ref }}
          title: "Merge changes from ${{ github.ref }}"
          labels: "Hotfix release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
