name: RELEASE-PROD

on:
  workflow_dispatch:
    inputs:
      hotfix:
        description: "Is this a hotfix release?"
        required: false
        default: "false"

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write
  actions: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: npm run release:version
          publish: npm run release:tag
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-pr
      - name: Set PR Target Branch
        run: |
          if [[ "${{ github.event.inputs.hotfix }}" == "true" ]]; then
            echo "::set-output name=target_branch::hotfix_release_branch"
          else
            echo "::set-output name=target_branch::main"
          fi
        id: set-target-branch
      - name: Update PR target branch
        run: |
          pr_url=$(jq -r '.pullRequest.url' <${{ steps.create-pr.outputs.outputFile }})
          pr_number=$(jq -r '.pullRequest.number' <${{ steps.create-pr.outputs.outputFile }})
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X PATCH \
            -d "{\"base\":\"${{ steps.set-target-branch.outputs.target_branch }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number
