name: RELEASE-PROD

# This workflow is manually triggered and will call changesets to collect up all
# changes ready for release and open a PR for approval. The newly opened PR will
# need to be closed and opened to trigger `cd-changesets-tests.yml`

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write
  actions: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: npm run release:version
          publish: npm run release:tag
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
