name: RELEASE-PROD

on:
  workflow_dispatch:
    inputs:
      hotfix:
        type: choice
        description: "Is this a hotfix release?"
        required: false
        default: "false"
        options:
          - true
          - false

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write
  actions: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      # Only run if hotfix flag is true
      - name: Bump Version, Tag Release, and Create Pull Request
        if: ${{ github.event.inputs.hotfix == 'true' }}
        run: |
          npm run release:version
          npm run release:tag

          branch_name="hotfix_release_branch"
          echo "Creating Pull Request to $branch_name..."
          echo "::set-output name=branch_name::$branch_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only run if hotfix flag is true
      - name: Create Pull Request to hotfix_release_branch
        if: ${{ github.event.inputs.hotfix == 'true' }}
        uses: peter-evans/create-pull-request@v3
        with:
          base: hotfix_release_branch
          branch: ${{ steps.create-branch.outputs.branch_name }}
          title: "Merge changes from ${{ steps.create-branch.outputs.branch_name }}"
          labels: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
