name: RELEASE-PROD

on:
  workflow_dispatch:
    inputs:
      hotfix:
        type: choice
        description: "Is this a hotfix release?"
        required: false
        default: "false"
        options:
          - true
          - false

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write
  actions: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.hotfix == 'true' && github.head_ref || github.ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Create Changeset Release Branch
        id: create-changeset-branch
        run: |
          branch_name="changeset-release/$(basename ${GITHUB_REF})"
          git checkout -b "$branch_name"
          pnpm run release:version
          git add .
          git commit -m "Version Packages"
          git push origin HEAD:$branch_name --force
          echo "::set-output name=branch_name::$branch_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR Target Branch
        id: set-target-branch
        run: |
          if [[ "${{ github.event.inputs.hotfix }}" == "true" ]]; then
            echo "hotfix_release_branch" > target_branch.txt
          else
            echo "main" > target_branch.txt
          fi

      - name: Debug
        run: |
          echo "Branch name from create-changeset-branch step: ${{ steps.create-changeset-branch.outputs.branch_name }}"
          echo "Target branch from set-target-branch step: ${{ steps.set-target-branch.outputs.target_branch }}"

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Release"
          branch: ${{ steps.create-changeset-branch.outputs.branch_name }}
          title: "Release"
          body: "This is the automated release pull request."
          base: ${{ steps.set-target-branch.outputs.target_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-pr

      - name: Update PR Target Branch for Hotfix
        if: ${{ github.event.inputs.hotfix == 'true' }}
        run: |
          pr_number=$(jq -r '.number' < "${{ steps.create-pr.outputs.pull-request-url }}")
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X PATCH \
            -d "{\"base\":\"hotfix_release_branch\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"
