name: RELEASE PROD VERSION

on:
  pull_request:
    branches:
      - main
      - release
    types:
      - closed

permissions:
  id-token: write
  contents: write

jobs:
  fetch-version:
    if: ${{ (github.event.pull_request.merged == true) && (startsWith(github.head_ref, 'changeset-release/')) }}
    name: Fetch Version
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.get.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch Version
        id: get
        run: |
          export RELEASE_VERSION=$(cat package.json | grep '"version":' | tr -d '"' | tr -d 'version: ' | tr -d ',')
          echo $RELEASE_VERSION
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Create Tag
        run: |
          git tag v${{ env.RELEASE_VERSION }}
          git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.RELEASE_VERSION }}"

  prod-cd:
    name: PROD
    runs-on: ubuntu-latest
    needs: fetch-version
    if: ${{ (github.event.pull_request.merged == true) && (startsWith(github.head_ref, 'changeset-release/')) }}
    steps:
      - name: Simulate CD
        run: |
          echo "Starting deployment to production..."
          echo "Deploying version $RELEASE_VERSION to production..."
      - name: Check if Hotfix
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "release" ]]; then
            echo "::set-output name=hotfix::true"
          else
            echo "::set-output name=hotfix::false"
          fi
        id: check-hotfix
      - name: Create PR from release to main
        if: ${{ steps.check-hotfix.outputs.hotfix == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: main
          title: "Hotfix: Merge release branch into main"
          body: "This PR merges the hotfix from the release branch into the main branch."
          commit-message: "Hotfix: Merge release branch into main"
          labels: hotfix
          delete-branch: false
