name: RELEASE PROD VERSION

on:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: write

jobs:
  fetch-version:
    if: ${{ github.event.pull_request.merged == true && ((startsWith(github.event.pull_request.head.ref, 'changeset-release/') && github.event.pull_request.base.ref == 'main') || (startsWith(github.event.pull_request.head.ref, 'hotfix/') && github.event.pull_request.base.ref == 'hotfix_release_branch')) }}
    name: Fetch Version
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.get.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch Version
        id: get
        run: |
          export RELEASE_VERSION=$(jq -r '.version' package.json)
          echo $RELEASE_VERSION
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
      - name: Create Tag
        run: |
          git tag v${{ env.RELEASE_VERSION }}
          git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.RELEASE_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prod-cd:
    name: PROD
    runs-on: ubuntu-latest
    needs: fetch-version
    if: ${{ github.event.pull_request.merged == true && ((startsWith(github.event.pull_request.head.ref, 'changeset-release/') && github.event.pull_request.base.ref == 'main') || (startsWith(github.event.pull_request.head.ref, 'hotfix/') && github.event.pull_request.base.ref == 'hotfix_release_branch')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Simulate CD
        run: |
          echo "Starting deployment to production..."
          echo "Deploying version ${{ needs.fetch-version.outputs.RELEASE_VERSION }} to production..."
          CONTENTS=""
          for markdown in src/*.md; do
            CONTENTS="$CONTENTS\n$(cat $markdown)"
          done
          echo -e $CONTENTS

      - name: Delete Existing hotfix_release_branch
        if: ${{ github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'changeset-release/') }}
        run: |
          git push origin --delete hotfix_release_branch || true

      - name: Create hotfix_release_branch from Latest Tag
        if: ${{ github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'changeset-release/') }}
        run: |
          git fetch origin --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout -b hotfix_release_branch $LATEST_TAG
          git push origin hotfix_release_branch --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Protect hotfix_release_branch
        if: ${{ github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'changeset-release/') }}
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.luke-cage-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/hotfix_release_branch/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":true,"required_pull_request_reviews":{"dismiss_stale_reviews":true},"restrictions":null}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create hotfix-to-main Branch
        if: ${{ github.event.pull_request.base.ref == 'hotfix_release_branch' && startsWith(github.event.pull_request.head.ref, 'hotfix/') }}
        run: |
          git fetch origin --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
          git checkout -b hotfix-to-main
          git push origin hotfix-to-main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to Main
        if: ${{ github.event.pull_request.base.ref == 'hotfix_release_branch' && startsWith(github.event.pull_request.head.ref, 'hotfix/') }}
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: hotfix-to-main
          title: "Merge hotfix changes to main"
          body: "This PR merges hotfix changes from the latest tag to the main branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
