name: Mirror PR to main

# This workflow is designed to be run after a feature is merged in to the
# integration branch - `development`. It opens an identical PR from the feature branch to
# the main branch after the feature branch has been merged to `development`.

on:
  pull_request:
    branches:
      - development
    types:
      - closed

jobs:
  mirror-pr:
    if: (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development')
    name: Mirror PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mirror PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.pull_request.title }}
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          base: main
          branch: ${{ github.event.pull_request.head.ref }}
          labels: "staging"
          author: ${{ github.event.pull_request.user.login }}
          delete-branch: true
